name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: dapps-substreams-server
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
  deploy:
    strategy:
      matrix:
        network: [eth, polygon]
        env: [dev, stg]
    name: "Deploy to: ${{ matrix.env }}"
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    steps:
      - name: Trigger deployment
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "quay.io/decentraland/dapps-substreams-server:${{ github.sha }}"
          serviceName: "dapps-${{ matrix.network }}-substreams-server"
          env: ${{ matrix.env }}
          token: ${{ secrets.GITHUB_TOKEN }}
