name: CI/CD on main branch

on:
  push:
    branches:
      - 'main'

jobs:
  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    strategy:
      matrix:
        network: [eth, polygon]
    with:
      service-name: dapps-${{ matrix.network }}-substreams-server
      deployment-environment: dev stg
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
